name: 'Generate and Commit Docs'

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    inputs:
      source-path:
        description: 'Source path containing the .h files'
        required: true
      target-path:
        description: 'Target path or file for the markdown documentation'
        required: true
      exclude-pattern:
        description: 'Pattern for excluding files (e.g. "*/test/*")'
      include-cpp:
        description: 'Include .cpp files'
      commit:
        description: 'Boolean flag to indicate whether to commit changes'
        default: false
      commit-message:
        description: 'Commit message'
        default: 'Update documentation'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cache Node modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Install render-docs
      run: npm install sebromero/render-docs
      if: steps.cache-node-modules.outputs.cache-hit != 'true'

    - name: Cache render-docs
      id: cache-render-docs
      uses: actions/cache@v2
      with:
        path: |
          node_modules/render-docs
        key: ${{ runner.os }}-render-docs-${{ hashFiles('node_modules/render-docs/package.json') }}
        restore-keys: |
          ${{ runner.os }}-render-docs-

    - name: Run Docs Generation
      run: npx render-docs -- ${{ inputs.source-path }} ${{ inputs.target-path }} ${{ inputs.exclude-pattern ? '-e ' + inputs.exclude-pattern : '' }} ${{ inputs.include-cpp ? '-c' : '' }}
      if: steps.cache-render-docs.outputs.cache-hit != 'true'

    - name: Commit Docs
      if: inputs.commit
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git commit -m "${{ inputs.commit-message }}"
        git push
